# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ObesityWeek Docs
owner: ObesityWeek, LLC
email: it@asmbs.org
baseurl: /ow-docs
theme: brand-purple
fixedNav: 'true'

# Build settings
markdown: kramdown
include:
    - "_pages"
exclude:
    - "README.md"
